name: Publish
on:
#  workflow_dispatch: # todo: requires to be merged to default branch to work
  push:
    branches:
      - jdk17-scala2.12.15
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      - name: Build and publish maven artifacts
        run: sbt "+clean; +publishSigned"
      - name: Setup buildx builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push images
        run: ./build-images.sh --push
