name: Publish
on:
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      SONATYPE_USERNAME: ${{ secrets.SONATYPE_USERNAME }}
      SONATYPE_PASSWORD: ${{ secrets.SONATYPE_PASSWORD }}
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 11
          cache: sbt
      - uses: sbt/setup-sbt@v1
      - name: Import GPG key
        id: import_gpg
        uses: crazy-max/ghaction-import-gpg@v5
        with:
          gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
          passphrase: ${{ secrets.GPG_PRIVATE_KEY_PASSWORD }}
      - name: Check if snapshot version
        run:  echo "IS_SNAPSHOT=$(sbt --no-colors -Dsbt.supershell=false 'show isSnapshot' | grep 'info' | tail -1 | awk '{print $2}')" >> $GITHUB_ENV
      - name: Build and publish release version to maven
        if: ${{ env.IS_SNAPSHOT == 'true' }}
        run: sbt "+clean; +publishSigned; sonatypeBundleRelease"
      - name: Build and publish snapshot version to maven
        if: ${{ env.IS_SNAPSHOT == 'false' }}
        run: sbt "+clean; +publishSigned"
      - name: Setup buildx builder
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/amd64,linux/arm64
          config-inline: |
            [worker.oci]
              max-parallelism = 1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USER }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push images
        run: ./build-images.sh --push
